### PR TITLE
BIT-47 Fix crash when installing APKs on Android N

### LINKED ISSUE #42: App crashes when downloading / installing build
Actual Result
The app crashes when a build is downloaded / installed

Expected Result
App shouldn't crash

Reproducibility 4/4

Steps to reproduce
1. Open the app and select a project, e.g. ONA_OnAir_Android
2. Select the newest develop, afterwards "Artifacts"
3. Select either the signed or unsigned version
Observe: After a few seconds the app crashes 

SM-G920F, Android 7, Store-version 1.2

Ticket BIT-47

### PR DESCRIPTION
**Pull request by ubuntudroid**
Fixes #42

### CODE REVIEW

File: app/src/main/java/io/stanwood/bitrise/ui/artifacts/vm/ArtifactItemViewModel.kt [hunk 1]
```diff
@@ -157,7 +157,7 @@ class ArtifactItemViewModel(
     }
 
     private fun getDownloadedApkUri(downloadId: Long): Uri {
-        return if (Build.VERSION.SDK_INT > Build.VERSION_CODES.N) {
+        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
```
Comment (mmoczkowski) [inline app/src/main/java/io/stanwood/bitrise/ui/artifacts/vm/ArtifactItemViewModel.kt]: NO WAY
